//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class BackgroundInfo {
    
    private string cachedModeField;
    
    private CachedLibrary[] cachedLibrariesField;
    
    /// <remarks/>
    public string CachedMode {
        get {
            return this.cachedModeField;
        }
        set {
            this.cachedModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public CachedLibrary[] CachedLibraries {
        get {
            return this.cachedLibrariesField;
        }
        set {
            this.cachedLibrariesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CachedLibrary {
    
    private string cachedTypeField;
    
    private string nameField;
    
    private string cachedBackgroundFileField;
    
    /// <remarks/>
    public string CachedType {
        get {
            return this.cachedTypeField;
        }
        set {
            this.cachedTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string CachedBackgroundFile {
        get {
            return this.cachedBackgroundFileField;
        }
        set {
            this.cachedBackgroundFileField = value;
        }
    }
}
